---
# These are derived from the top-level inventory vars:

compute_common_groups:
  - name: cluster
    system: true

compute_common_users:
  - name: ansible
    groups: [wheel]
    shell: /bin/bash
    authorized_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub', errors='ignore') }}"

compute_common_server_ip: "{{ network_config.server_ip }}"
compute_common_python_interpreter: "{{ ansible_python_interpreter | default('/usr/bin/python3') }}"
