---
# These are derived from the top-level inventory vars:

controller_common_groups:
  - name: cluster
    system: true

controller_common_packages:
  - vim
  - git
  - curl
  - net-tools
  - python3
  - python3-devel
  - python3-pip
  - rsync
  - tmux
  - policycoreutils-python-utils
  - python3-netaddr

controller_common_users:
  - name: ansible
    groups: [wheel]
    shell: /bin/bash
    authorized_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub', errors='ignore') }}"
